// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6yVHUzVNJ2I04Ne7M30dJEGPcMAIF9V4',
    appId: '1:428648053308:web:eef960ebbb59b8df64a139',
    messagingSenderId: '428648053308',
    projectId: 'zippandgo-37ae8',
    authDomain: 'zippandgo-37ae8.firebaseapp.com',
    storageBucket: 'zippandgo-37ae8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbTESr6Sl_N9kzFbNIduqoO-pZIVT2OTY',
    appId: '1:428648053308:android:fadac0ef9093a45b64a139',
    messagingSenderId: '428648053308',
    projectId: 'zippandgo-37ae8',
    storageBucket: 'zippandgo-37ae8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqbzGIh8JnOBoJjILCRXfJNlBUJgPJGKA',
    appId: '1:428648053308:ios:2d2da0146e9656e764a139',
    messagingSenderId: '428648053308',
    projectId: 'zippandgo-37ae8',
    storageBucket: 'zippandgo-37ae8.firebasestorage.app',
    androidClientId: '428648053308-7qr9svphbk8jj86rqfh1jlmkug5jfgf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.motorbikeParcelDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqbzGIh8JnOBoJjILCRXfJNlBUJgPJGKA',
    appId: '1:428648053308:ios:2d2da0146e9656e764a139',
    messagingSenderId: '428648053308',
    projectId: 'zippandgo-37ae8',
    storageBucket: 'zippandgo-37ae8.firebasestorage.app',
    androidClientId: '428648053308-7qr9svphbk8jj86rqfh1jlmkug5jfgf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.motorbikeParcelDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6yVHUzVNJ2I04Ne7M30dJEGPcMAIF9V4',
    appId: '1:428648053308:web:caf8a2247c0c2edd64a139',
    messagingSenderId: '428648053308',
    projectId: 'zippandgo-37ae8',
    authDomain: 'zippandgo-37ae8.firebaseapp.com',
    storageBucket: 'zippandgo-37ae8.firebasestorage.app',
  );

}